version: '3'

services:
  prontogram-frontend:
    image: prontogram-frontend
    container_name: prontogram-frontend
    ports:
      - 4173:4173
    build:
      dockerfile: ./Dockerfile
    networks:
      - prontogram-net
      - acmesky

networks:
  prontogram-net:
    name: prontogram-net
    driver: bridge
  acmesky:
    external: true
