version: '3'

services:
  prontogram-frontend:
    image: prontogram-frontend
    container_name: prontogram-frontend
    ports:
      - "4173:80"
    build:
      dockerfile: ./Dockerfile
    networks:
      - prontogram-net
      - acmesky

networks:
  prontogram-net:
    external: true
  acmesky:
    external: true